pluralsight/node/02_course_demo/VacationTrackerAdmin/Models/Employee.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace VacationTrackerAdmin.Models
{
    public class Employee
    {
        public int Id { get; set; }
        
        [Display(Name = "Badge#")]
        public int BadgeNumber { get; set; }

        [Display(Name = "First Name")]
        public string FirstName { get; set; }

        [Display(Name = "Last Name")]
        public string LastName { get; set; }

        [Display(Name = "Accrual Rate")]
        public float VacationAccrualRate { get; set; }

        [Display(Name = "Total Hours")]
        public float VacationAccrued { get; set; }
        
        public List<Vacation> Vacations { get; set; } = new List<Vacation>();
    }
}

pluralsight/node/02_course_demo/VacationTrackerAdmin/Models/Vacation.cs
using System;

namespace VacationTrackerAdmin.Models
{
    public class Vacation
    {
        public int Id { get; set; }
        public DateTime StartDate { get; set; }
        public float Duration { get; set; }
        public bool IsCancelled { get; set; }
    }
}

pluralsight/node/02_course_demo/VacationTrackerAdmin/Controllers/EmployeeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using VacationTrackerAdmin.Repositories;
using VacationTrackerAdmin.Models;

// For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860

namespace VacationTrackerAdmin.Controllers
{
    [Route("employees")]
    public class EmployeeController : Controller
    {
        private IEmployeeRepository _employeeRepository;

        public EmployeeController(IEmployeeRepository employeeRepository)
        {
            _employeeRepository = employeeRepository;
        }

        [Route("add")]
        [HttpGet]
        public async Task<IActionResult> GetAdd()
        {
            return View("Add");
        }

        [Route("add")]
        [HttpPost]
        public async Task<IActionResult> PostAdd(List<Employee> employees)
        {
            employees = employees.Where(e => e.BadgeNumber != 0).ToList();

            await _employeeRepository.SaveAllAsync(employees);

            return new RedirectToActionResult("index", "home", null);
        }

        [Route("update")]
        [HttpGet]
        public IActionResult GetId()
        {
            return View("IdForm");
        }

        [Route("", Name = "getUpdate")]
        [HttpGet]
        public async Task<IActionResult> GetUpdate(int badgeNumber)
        {
            var employee = await _employeeRepository.GetByBadgeNumberAsync(badgeNumber);

            if (employee == null)
            {
                return new RedirectToActionResult("index", "home", null);
            }

            return View("Update", employee);
        }

        [Route("")]
        [HttpPost]
        public async Task<IActionResult> PostUpdate(Employee employee)
        {
            employee = await _employeeRepository.SaveAsync(employee);

            return new RedirectToRouteResult("getUpdate", new { badgeNumber = employee.BadgeNumber });
        }
    }
}

pluralsight/node/02_course_demo/VacationTrackerAdmin/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace VacationTrackerAdmin.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Error()
        {
            return View();
        }
    }
}

pluralsight/node/02_course_demo/VacationTrackerAdmin/Controllers/ReportController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using VacationTrackerAdmin.Repositories;

// For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860

namespace VacationTrackerAdmin.Controllers
{
    [Route("report")]
    public class ReportController : Controller
    {
        private IEmployeeRepository _employeeRepository;

        public ReportController(IEmployeeRepository employeeRepository)
        {
            _employeeRepository = employeeRepository;
        }

        [Route("")]
        public async Task<IActionResult> Index()
        {
            var employees = await _employeeRepository.GetAllAsync();
            return View(employees);
        }
    }
}

pluralsight/node/02_course_demo/VacationTrackerAdmin/Views/Employee/Add.cshtml
@{
    ViewData["BaseCssClass"] = "add-employee";
    ViewData["Title"] = "Add Employees";
}

@model VacationTrackerAdmin.Models.Employee

<h1 class="text-center">Add Employees</h1>

@using (Html.BeginForm())
{
    <div class="row title">
        <div class="columns small-2">
            @Html.LabelFor(m => m.Id)
        </div>
        <div class="columns small-2">
            @Html.LabelFor(m => m.BadgeNumber)
        </div>
        <div class="columns small-2">
            @Html.LabelFor(m => m.FirstName)
        </div>
        <div class="columns small-2">
            @Html.LabelFor(m => m.LastName)
        </div>
        <div class="columns small-2">
            @Html.LabelFor(m => m.VacationAccrualRate)
        </div>
        <div class="columns small-2">
            @Html.LabelFor(m => m.VacationAccrued)
        </div>
    </div>

    @for (var i = 0; i < 5; i++)
    {
        <div class="row">
            <div class="columns small-2">
                new
            </div>
            <div class="columns small-2">
                <input type="number" name="[@i].BadgeNumber" value="" min="0" />
            </div>
            <div class="columns small-2">
                <input type="text" name="[@i].FirstName" value="" />
            </div>
            <div class="columns small-2">
                <input type="text" name="[@i].LastName" value="" />
            </div>
            <div class="columns small-2">
                <input type="number" name="[@i].VacationAccrualRate" value="" min="0" step="0.01"/>
            </div>
            <div class="columns small-2">
                <input type="number" name="[@i].VacationAccrued" value="" min="0" step="0.01"/>
            </div>
        </div>
    }

    <div class="row">
        <div class="columns small-2 small-offset-10">
            <button type="submit">Submit</button>
        </div>
    </div>
}



pluralsight/node/02_course_demo/VacationTrackerAdmin/Views/Employee/IdForm.cshtml
@{
    ViewData["BaseCssClass"] = "id-form";
    ViewData["Title"] = "Employee ID Request";
}

<h1 class="text-center">Please Enter a Badge Number</h1>

<form asp-controller="Employee" asp-action="GetUpdate" method="get">
    <div class="row">
        <div class="columns small-4 small-offset-4 end">
            Employee Badge Number
        </div>
        <div class="columns small-4 small-offset-4 end">
            <input type="number" name="badgeNumber" value="" />
        </div>
    </div>
    <div class="row">
        <div class="columns small-2 small-offset-7 end">
            <button type="submit">Submit</button>
        </div>
    </div>
</form>

pluralsight/node/02_course_demo/VacationTrackerAdmin/Views/Employee/Update.cshtml
@{
    ViewData["BaseCssClass"] = "update-employee";
    ViewData["Title"] = "Update Employee";
}

@model VacationTrackerAdmin.Models.Employee

<h1 class="text-center">Update Employee</h1>

@using (Html.BeginForm())
{

    <div class="row">
        <div class="column small-10 small-offset-1 end">
            <div class="row">
                <h2 class="columns small-12">
                    Employee Data
                </h2>
            </div>
            <div class="row">
                <div class="columns small-6">
                    @Html.DisplayNameFor(m => m.Id)
                    <br />
                    @Html.ValueFor(m => m.Id)
                    @Html.HiddenFor(m => m.Id)
                </div>
                <div class="columns small-6">
                    @Html.LabelFor(m => m.BadgeNumber)
                    @Html.TextBoxFor(m => m.BadgeNumber, "", new { type = "number" })
                </div>
            </div>
            <div class="row">
                <div class="columns small-6">
                    @Html.LabelFor(m => m.FirstName)
                    @Html.TextBoxFor(m => m.FirstName)
                </div>
                <div class="columns small-6">
                    @Html.LabelFor(m => m.LastName)
                    @Html.TextBoxFor(m => m.LastName)
                </div>
            </div>

            <div class="row">
                <div class="columns small-6">
                    @Html.LabelFor(m => m.VacationAccrualRate)
                    @Html.TextBoxFor(m => m.VacationAccrualRate)
                </div>
                <div class="columns small-6">
                    @Html.LabelFor(m => m.VacationAccrued)
                    @Html.TextBoxFor(m => m.VacationAccrued)
                </div>
            </div>
            <div class="row">
                <h2 class="columns small-12">
                    Vacations
                </h2>
                <div class="row">
                    <div class="columns small-2 text-center">
                        Id
                    </div>
                    <div class="columns small-4">
                        Start Date
                    </div>
                    <div class="columns small-4">
                        Duration
                    </div>
                    <div class="columns small-2 text-center">
                        Cancelled?
                    </div>
                </div>
            </div>
            <br />
            @for (var i = 0; i < Model.Vacations.Count; i++)
            {
                <div class="row">
                    <div class="columns small-2 text-center">
                        @Model.Vacations[i].Id
                        @Html.HiddenFor(m => Model.Vacations[i].Id);
                    </div>
                    <div class="columns small-4">
                        @Html.TextBoxFor(m => Model.Vacations[i].StartDate, "{0:yyyy-MM-dd}", new { type = "date" })
                    </div>
                    <div class="columns small-4">
                        @Html.TextBoxFor(m => Model.Vacations[i].Duration, "", new { type = "number" })
                    </div>
                    <div class="columns small-2 text-center">
                        @Html.CheckBoxFor(m => Model.Vacations[i].IsCancelled)
                    </div>
                </div>
            }
        </div>
    </div>
    <div class="row">
        <div class="columns small-2 small-offset-10">
            <button type="submit">Submit</button>
        </div>
    </div>
}




pluralsight/node/02_course_demo/VacationTrackerAdmin/Views/Home/Index.cshtml
@{
    ViewData["BaseCssClass"] = "home";
    ViewData["Title"] = "Home";

}
<div class="row">
    <div class="columns small-10 small-offset-1 end">
        <h1 class="text-center title">Vacation Tracking Adminstrations</h1>
    </div>
</div>
<div class="row">
    <div class="columns small-12 nav-menu">
        <div class="row">
            <a asp-controller="Employee" asp-action="GetAdd" 
               class="columns small-8 small-offset-2 end menu-item add" >
                Add Employees
            </a>
        </div>
        <div class="row">
            <a asp-controller="Employee" asp-action="GetId" 
               class="columns small-8 small-offset-2 end menu-item update">
                Update Employee
            </a>
        </div>
        <div class="row">
            <a asp-controller="Report" asp-action="Index"
               class="columns small-8 small-offset-2 end menu-item report">
                Generate Report
            </a>
        </div>
    </div>
</div>

pluralsight/node/02_course_demo/VacationTrackerAdmin/Views/Report/Index.cshtml
@{
    ViewData["BaseCssClass"] = "report";
    ViewData["Title"] = "Report";

}
@model List<VacationTrackerAdmin.Models.Employee>

<div class="row">
    <div class="columns small-10 small-offset-1 end">
        <h1 class="text-center title">Vacation Usage Report</h1>
    </div>
</div>
@foreach (var emp in Model)
{
    <fieldset>
        <legend><h3>@emp.LastName, @emp.FirstName - @emp.BadgeNumber</h3></legend>
        <div class="row">
            <h4 class="columns small-12">
                Vacations
            </h4>
            <div class="columns small-12">
                <div class="row">
                    <div class="columns small-2">
                        Id
                    </div>
                    <div class="columns small-4">
                        Start Date
                    </div>
                    <div class="columns small-4">
                        Duration
                    </div>
                    <div class="columns small-2">
                        Cancelled?
                    </div>
                </div>
            </div>
        </div>
        <hr />
        @foreach (var vac in emp.Vacations)
        {
            <div class="row vacation-item">
                <div class="columns small-2">
                    @vac.Id
                </div>
                <div class="columns small-4">
                    @vac.StartDate.ToString("dd-MMM-yyyy")
                </div>
                <div class="columns small-4">
                    @vac.Duration
                </div>
                <div class="columns small-2">
                    @{
                        if (vac.IsCancelled)
                        {
                            @:Cancelled
                        }
                        else
                        {
                            @:Active

                        }
                    }
                </div>
            </div>
        }
    </fieldset>
}

pluralsight/node/02_course_demo/VacationTrackerAdmin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Vacation Tracking Tool - s@ViewData["Title"]</title>

    <link href="~/node_modules/zurb-foundation/css/normalize.css" rel="stylesheet" />
    <link href="~/node_modules/zurb-foundation/css/foundation.css" rel="stylesheet" />
    <link href="~/css/font-awesome.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <div class="container">
        <div class="row @ViewData["BaseCssClass"]">
            <div class="columns small-12">
                @RenderBody()
            </div>
        </div>
    </div>

    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("scripts", required: false)
</body>
</html>